management:
    security:
        enabled: false

logging: # <----New sections below
    level:
        root: WARN
        com:
            orangeandbronze: DEBUG

greeting:
    displayFortune: true

quoteServiceURL: http://quotesondesign.com/wp-json/posts?filter[orderby]=rand&filter[posts_per_page]=1
